Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -20,14 +20,23 @@ jobs:
         distribution: 'temurin'
         cache: gradle
 
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-
-    - name: Build with Gradle
-      run: ./gradlew build
+    - name: Change wrapper permissions and Build
+      run: |
+        if [ -f gradlew ]; then
+          chmod +x gradlew
+          ./gradlew build
+        elif [ -f android/gradlew ]; then
+          cd android
+          chmod +x gradlew
+          ./gradlew build
+        else
+          echo "Gradlew file not found anywhere!"
+          exit 1
+        fi
 
     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
         name: AmbuTrack-debug-apk
-        path: app/build/outputs/apk/debug/app-debug.apk
+        path: "**/build/outputs/apk/debug/app-debug.apk"
+
